const ArrOfResPhotos=[
    {
        id:1,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/resPHOTO/pizzaHutImage.jpg"),
    },
    {
        id:2,
        photoURL:require("../assets/DishImages/resCode2_DominosPizza/resPHOTO/dominosPhoto.png"),
    },
    {
        id:3,
        photoURL:require("../assets/DishImages/resCode3_OshiOshi/resPHTO/oshiPhoto.jpg"),
    },
    {
        id:4,
        photoURL:require("../assets/DishImages/resCode4_Mcdonalds/resPhoto/mcdonalds.png"),
    },
    {
        id:5,
        photoURL:require("../assets/DishImages/resCode5_Japanika/resPhoto/japanika.jpg"),
    },
    {
        id:6,
        photoURL:require("../assets/DishImages/resCode6_BurgerRanch/resPhoto/burgerRanch.jpeg"),
    },
    {
        id:7,
        photoURL:"../assets/DishImages/resCode7_Juvani/resPhoto/juvani.jpg",
    },
    {
        id:8,
        photoURL:require("../assets/DishImages/resCode8_JohnnyCrispy/resPhoto/JhonnyCrispy.jpg"),
    }, 
    ]
    export default ArrOfResPhotos;