const ArrOfResDishes1=[
    {
        id:1,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_1_.png"),
    },
    {
        id:2,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_2_Pizza_frikase_.png"),
    },
    {
        id:3,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_3_.png"),
    },
    {
        id:4,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_4_.png"),
    },
    {
        id:5,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_5_.png"),
    },
    {
        id:6,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_6_.png"),
    },
    {
        id:7,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_7_.png"),
    },
    {
        id:8,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_8_.png"),
    }, 
    {
        id:9,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_9_.png"),
    },
    {
        id:10,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_10_.png"),
    },
    {
        id:11,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_11_.png"),
    },
    {
        id:12,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pizzas/dishCode_12_.png"),
    },
    {
        id:13,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pastas_n_kishes/dishCode_13_.png"),
    },
    {
        id:14,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pastas_n_kishes/dishCode_14_.png"),
    },
    {
        id:15,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pastas_n_kishes/dishCode_15_.png"),
    },
    {
        id:16,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pastas_n_kishes/dishCode_16_.png"),
    },
    {
        id:17,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pastas_n_kishes/dishCode_17_.png"),
    },
    {
        id:18,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/pastas_n_kishes/dishCode_18_.png"),
    },
    {
        id:19,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_19_.png"),
    },
    {
        id:20,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_20_.png"),
    },
    {
        id:21,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_21_.png"),
    },
    {
        id:22,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_22_filo.png"),
    },
    {
        id:23,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_23_filo_tres.png"),
    },
    {
        id:24,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_24.png"),
    },
    {
        id:25,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_25.png"),
    },
    {
        id:26,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_26.png"),
    },
    {
        id:27,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_27.png"),
    },
    {
        id:28,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_28.png"),
    },
    {
        id:29,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_29.png"),
    },
    {
        id:30,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_30.png"),
    },
    {
        id:31,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_31.png"),
    },
    {
        id:32,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_32.png"),
    },
    {
        id:33,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/side_dishes/dishCode_33.png"),
    },
    {
        id:34,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/salats/dishCode_34.png"),
    },
    {
        id:35,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/salats/dishCode_35.png"),
    },
    {
        id:36,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/salats/dishCode_36.png"),
    },
    {
        id:37,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/desert/dishCode_37.png"),
    },
    {
        id:38,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/desert/dishCode_38.png"),
    },
    {
        id:39,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/desert/dishCode_39.png"),
    },
    {
        id:40,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/desert/dishCode_40.png"),
    },
    {
        id:41,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/coca_cola_1.5_41.png"),
    },
    {
        id:42,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/coca_cola_small42.jpg"),
    },
    {
        id:43,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/cola_diet_1.5_43.jpg"),
    },
    {
        id:44,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/cola_diet_small_44.png"),
    },
    {
        id:45,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/cola_zero_1.5_45.jpg"),
    },
    {
        id:46,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/cola_zero_small_46.jpg"),
    },
    {
        id:47,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/fanta_1.5_47.jpg"),
    },
    {
        id:48,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/drinks_48.png"),
    },
    {
        id:49,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/fuze_tea_1.5_49.jpg"),
    },
    {
        id:50,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/fuze_tea_small_50.jpg"),
    },
    {
        id:51,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/grapes_1.5_51.jpg"),
    },
    {
        id:52,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/prigat_grapes_small_52.jpg"),
    },
    {
        id:53,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/prigat_oranges_1.5_53.jpg"),
    },
    {
        id:54,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/prigat_oranges_small_54.jpg"),
    },
    {
        id:55,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/sprite_1.5_55.jpg"),
    },
    {
        id:35,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/sprite_diet_1.5_56.jpg"),
    },
    {
        id:56,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/sprite_diet_small_57.jpg"),
    },
    {
        id:57,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/sprite_small_58.jpg"),
    },
    {
        id:58,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/water_1.5_59.png"),
    },
    {
        id:59,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/drinks/water_small_60.png"),
    },
    {
        id:60,
        photoURL:require("../assets/DishImages/resCode1_PizzaHut/desert/dishCode_40.png"),
    },
    ]
    export default ArrOfResDishes1;